[project]
name = "enviroweather-py"
version = "0.1.0"
description = "Documentation and demonstration of how to use The Enviroweather APIs in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.23.16",
    "openlayers>=0.1.6",
    "pandas>=3.0.5",
    "requests>=2.34.2",
]